### ISSUE TITLE
Link to Adyen/MerchantServer is missing

### ISSUE THREAD

**Issue by tjerkw** [Adyen/AdyenCheckout-android#1]
I"m not sure how to use the encryptedData, is this the CSE token? In the bottom it is mentioning to goto github.com/Adyen/Adyen/MerchantServer but that give me a 404

**Comment by andreivisan** [comment]
encryptedData is the CSE for the credit card data and that is to be sent to the merchant server and further to Adyen. 
The URL for the sample Merchant server has been updated as well.
